apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: multitool-config
              key: HTTP_PORT
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html
          items:
          - key: index.html
            path: index.html